language: node_js
node_js:
  - 14
  - 16
  - 18

sudo: false

cache:
  directories:
    - node_modules

install:
  - npm install --devDepenencies
script:
  - npm run test
after_script:
  - |
    npm install --save-dev coveralls
    coveralls < ./coverage/lcov.info